export default{
   "AF": "Afeganistão",
   "ZA": "Africa do Sul",
   "AL": "Albânia",
   "DE": "Alemanha",
   "AD": "Andorra",
   "AO": "Angola",
   "AI": "Anguilla",
   "AQ": "Antartica",
   "AG": "Antígua e Barbuda",
   "AN": "Antilhas Holandesas",
   "SA": "Arábia Saudita",
   "DZ": "Argélia",
   "AR": "Argentina",
   "AM": "Armênia",
   "AW": "Aruba",
   "AU": "Austrália",
   "AT": "Áustria",
   "AZ": "Azerbaidjão",
   "BS": "Bahamas",
   "BD": "Bangladesh",
   "BB": "Barbados",
   "BH": "Bareine",
   "BY": "Belarus",
   "BE": "Bélgica",
   "BZ": "Belize",
   "BX": "Benelux",
   "BJ": "Benin",
   "BM": "Bermudas",
   "BO": "Bolívia",
   "BA": "Bósnia e Herzegóvina",
   "BW": "Botswana",
   "BR": "Brasil",
   "BG": "Bulgária",
   "BN": "Brunei Darussalam",
   "BF": "Burkina Faso",
   "BI": "Burundi",
   "BT": "Butão",
   "CV": "Cabo Verde",
   "CM": "Camarões",
   "KH": "Camboja",
   "CA": "Canadá",
   "QA": "Catar",
   "KZ": "Cazaquistão",
   "TD": "Chade",
   "GW": "Guiné Bissau",
   "GQ": "Guine Equatorial",
   "HT": "Haiti",
   "NL": "Holanda",
   "HN": "Honduras",
   "HK": "Hong-Kong",
   "HU": "Hungria",
   "YE": "Iêmen",
   "BV": "Ilha Bouvet",
   "IM": "Ilha do Homem",
   "CX": "Ilha Natal",
   "NF": "Ilha Norfalk",
   "KY": "Ilhas Cayman",
   "CC": "Ilhas Cocos",
   "CK": "Ilhas Cook",
   "GG": "Ilhas do Canal",
   "FO": "Ilhas Faroe",
   "HM": "Ilhas Heard e McDonald",
   "FK": "Ilhas Malvinas",
   "MP": "Ilhas Marianas do Norte",
   "MH": "Ilhas Marshall",
   "UM": "Ilhas Menores",
   "SB": "Ilhas Salomão",
   "TC": "Ilhas Turks e Caicos",
   "VG": "Ilhas Virgens (Britânicas)",
   "VI": "Ilhas Virgens (U.S.)",
   "WF": "Ilhas Wallis e Futura",
   "IN": "India",
   "ID": "Indonésia",
   "IR": "Irã",
   "IQ": "Iraque",
   "IE": "Irlanda",
   "IS": "Islândia",
   "IL": "Israel",
   "ID": "Indonésia",
   "IR": "Irã",
   "IQ": "Iraque",
   "IE": "Irlanda",
   "IS": "Islândia",
   "IL": "Israel",
   "IT": "Itália",
   "JM": "Jamaica",
   "JP": "Japão",
   "JE": "Jersey",
   "PW": "Palau",
   "PA": "Panamá",
   "PG": "Papua Nova Guiné",
   "PK": "Paquistão",
   "PY": "Paraguai",
   "PE": "Peru",
   "PN": "Pitcairn",
   "PF": "Polinésia Francesa",
   "PL": "Polônia",
   "PR": "Porto Rico",
   "PT": "Portugal",
   "KE": "Quênia",
   "KG": "Quirguistão",
   "GB": "Reino Unido",
   "CF": "República Centro Africana",
   "KR": "República da Coréia",
   "MK": "República da Macedonia",
   "MD": "República da Moldova",
   "CD": "República Dem. Do Congo",
   "DO": "República Dominicana",
   "KP": "República Pop. Dem. da Coreia",
   "CZ": "República Tcheca",
   "TZ": "República Unida da Tanzânia",
   "RE": "Reunião",
   "RO": "Romênia",
   "RW": "Ruanda",
   "EH": "Saara Ocidental",
   "PM": "Saint Pierre e Miquelon",
   "AS": "Samoa Americana",
   "WS": "Samoa Ocidental",
   "SH": "Santa Helena",
   "LC": "Santa Lúcia",
   "SM": "São Marino",
   "VC": "São Vicente e Granadinas",
   "SL": "Serra Leoa",
   "SC": "Seychelles",
   "SY": "Síria",
   "LK": "Sri Lanka",
   "SD": "Sudão",
   "CL": "Chile",
   "CN": "China",
   "CY": "Chipre",
   "CO": "Colômbia",
   "KM": "Comores",
   "CG": "Congo",
   "CI": "Costa do Marfim",
   "CR": "Costa Rica",
   "HR": "Croácia",
   "CU": "Cuba",
   "DK": "Dinamarca",
   "DJ": "Djibuti",
   "DM": "Dominica",
   "EG": "Egito",
   "SV": "El Salvador",
   "AE": "Emirados Árabes Unidos",
   "EC": "Equador",
   "ER": "Eritréia",
   "EM": "Escritório para Harmonização no Mercado Interno",
   "SK": "Eslováquia",
   "SI": "Eslovenia",
   "ES": "Espanha",
   "US": "Estados Unidos da América",
   "EE": "Estônia",
   "ET": "Etiópia",
   "RU": "Federação Russa",
   "FJ": "Fiji",
   "PH": "Filipinas",
   "FI": "Finlândia",
   "FR": "França",
   "GA": "Gabão",
   "GM": "Gambia",
   "GE": "Geórgia",
   "GH": "Gana",
   "GS": "Geórgia do Sul e Ilhas Sandwich do Sul",
   "GI": "Gibraltar",
   "GD": "Granada",
   "GR": "Grécia",
   "GL": "Groenlândia",
   "GP": "Guadalupe",
   "GU": "Guam",
   "GT": "Guatemala",
   "GY": "Guiana",
   "GN": "Guine",
   "JO": "Jordânia",
   "KI": "Kiribati",
   "KW": "Kuwait",
   "LA": "Laos",
   "LS": "Lesoto",
   "LV": "Letônia",
   "LB": "Líbano",
   "LR": "Libéria",
   "LY": "Líbia",
   "LI": "Liechtenstein",
   "LT": "Lituânia",
   "LU": "Luxemburgo",
   "MO": "Macau",
   "MG": "Madagascar",
   "MY": "Malásia",
   "MW": "Malawi",
   "MV": "Maldivas",
   "ML": "Mali",
   "MT": "Malta",
   "MA": "Marrocos",
   "MQ": "Martinica",
   "MU": "Maurício",
   "MR": "Mauritânia",
   "MX": "México",
   "MM": "Mianmá",
   "FM": "Micronésia",
   "MZ": "Moçambique",
   "MC": "Mônaco",
   "MN": "Mongólia",
   "MS": "Mont Serrat",
   "ME": "Montenegro",
   "NA": "Namíbia",
   "NR": "Nauru",
   "NP": "Nepal",
   "NI": "Nicarágua",
   "NE": "Níger",
   "NG": "Nigéria",
   "NO": "Noruega",
   "NC": "Nova Caledônia",
   "NZ": "Nova Zelândia",
   "OM": "Omã",
   "OA": "Organização Africana de Propriedade Intelectual (OAPI)",
   "WO": "Organização Mundial de Propriedade Intelectual – OMPI (WIPO)",
   "AP": "Organização Regional de Propriedade Industrial Africana",
   "SE": "Suécia",
   "CH": "Suíça",
   "SR": "Suriname",
   "SJ": "Svalbard e Jan Mayen",
   "TJ": "Tadjiquistão",
   "TH": "Tailândia",
   "TW": "Taiwan",
   "TF": "Terras Austrais Francesas",
   "IO": "Territ.Britan.Oceano Índico",
   "PS": "Território Ocupado Palestino",
   "TL": "Timor-Leste",
   "TG": "Togo",
   "TK": "Tokelau",
   "TO": "Tonga",
   "TT": "Trinidad e Tobago",
   "TN": "Tunísia",
   "TM": "Turcomenistão",
   "TR": "Turquia",
   "TV": "Tuvalu",
   "UA": "Ucrânia",
   "UG": "Uganda",
   "UY": "Uruguai",
   "UZ": "Uzbequistão",
   "VU": "Vanuatu",
   "VA": "Vaticano",
   "VE": "Venezuela",
   "VN": "Vietnã",
   "YU": "Yugoslávia",
   "ZR": "Zaire",
   "ZM": "Zâmbia",
   "ZW": "Zimbábue",
   "KN": "São Cristovão e Nevis",
   "ST": "São Tomé e Príncipe",
   "SN": "Senegal",
   "RS": "Sérvia",
   "SG": "Singapura",
   "SO": "Somália",
   "SZ": "Suazilândia"
}